### ISSUE TITLE
[Cannot run a large number simultaneously.] Processing request is taking a little longer than usual [getting profile data]. Retrying in 57 seconds.

### ISSUE THREAD

**Issue by dsmddsmd** [Freddywhest/MemeFiBot-New#15]
![Screenshot_567](https://github.com/user-attachments/assets/2e5b027f-0545-4913-b07d-24bebc03c553)

Processing request is taking a little longer than usual [getting profile data]. Retrying in 57 seconds.

**Comment by Freddywhest** [comment]
It's not an error, it's a warning
