### ISSUE TITLE
ERROR: Server error while getting access token (Request failed with status code: 500)

### ISSUE THREAD

**Issue by skltujuh** [Freddywhest/MemeFiBot-New#22]
i'm login with query ids and this error happened
![image](https://github.com/user-attachments/assets/72123c19-3669-4950-86dc-fcedc95a9347)

**Comment by Color-maN** [comment]
> я захожу в систему с идентификаторами запросов, и произошла эта ошибка ![изображение](https://private-user-images.githubusercontent.com/101900015/371638189-72123c19-3669-4950-86dc-fcedc95a9347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjQ5NTgsIm5iZiI6MTcyNzQ2NDY1OCwicGF0aCI6Ii8xMDE5MDAwMTUvMzcxNjM4MTg5LTcyMTIzYzE5LTM2NjktNDk1MC04NmRjLWZjZWRjOTVhOTM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxOTE3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzAyYWEwM2RkNTdmMzc1NDllMTY2ODJlOWY2MWQxOTZmZWQ0YjE4NDRiZjIyN2E0MmEwNGMzY2ZjNzM2YjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7I1lnq88-D64fIeweJj1TWn1UwntOKNqcpP5fHL05Co)

There is a post in the author's telegram channel to solve MemeFi problems, maybe it will help here too. ->

For those encountering error 403 or error 500, follow these steps:

Ensure you have registered on Memefi via Telegram and tapped at least 10-20 times.

Make sure your Telegram account has a username.

After completing the above steps, delete the cache folder and restart the bot.
