### ISSUE TITLE
Processing request is taking a little longer than usual - [Validating query id]. Retrying in 300 seconds.

### ISSUE THREAD

**Issue by sabbir766757** [Freddywhest/MemeFiBot-New#24]
Processing request is taking a little longer than usual - [Validating query id]. Retrying in 300 seconds.

**Comment by sabbir766757** [comment]
![Screenshot from 2024-09-28 17-11-23](https://github.com/user-attachments/assets/42da99ca-69a9-4732-9b8f-c0603e61abbc)

**Comment by M4D3V2000** [comment]
same problem, but i changed my network and its fixed. try use vpn or proxy
