### ISSUE TITLE
Error while sending taps (Bad Request Exception) & Error while applying boost (Rate limited)

### ISSUE THREAD

**Issue by Color-maN** [Freddywhest/MemeFiBot-New#27]
These errors are constantly encountered. Can someone suggest the settings for RANDOM_APP, RANDOM_TURB_TAPE, DELAY_BETWEEN_TAGS, DELAY_BETWEEN_ATTACKS so that there are no such errors?

**Comment by Freddywhest** [comment]
Use proxies

**Comment by Color-maN** [comment]
> Использовать прокси

I use proxy for all sessions on http protocol and it doesn't help. The error occurs not every time, but every 4-5 times when requesting "taps", especially "turbo taps".

**Comment by Freddywhest** [comment]
Increase the delay time for turbo and taps
