### ISSUE TITLE
Authentication Error 

### ISSUE THREAD

**Issue by ashiqur9** [Freddywhest/MemeFiBot-New#3]
| ERROR | [memefi] | MemeFiBot-New | Error while getting access token: Request failed with status code: 403

**Comment by Freddywhest** [comment]
Refer to:
https://github.com/Freddywhest/MemeFiBot-New/issues/1#issuecomment-2372636917
Or
https://t.me/freddy_bots/83

**Comment by Freddywhest** [comment]
Fixed
