### ISSUE TITLE
need a little help

### ISSUE THREAD

**Issue by Mr-Mk7** [Freddywhest/MemeFiBot-New#32]
<img width="673" alt="Screenshot 2024-10-01 032048" src="https://github.com/user-attachments/assets/b65e37a2-4772-43fd-8da1-a8993db1b3ea">

            i am not understanding the instructions please help me from here ......

**Comment by Lastnet0709** [comment]
The Telegram account to be used must have a username
![image](https://github.com/user-attachments/assets/857c35cb-da75-411c-b4e7-7e0f94dfdf9c)
Add username > get new query

**Comment by Mr-Mk7** [comment]
> The Telegram account to be used must have a username ![image](https://private-user-images.githubusercontent.com/20702584/372261152-857c35cb-da75-411c-b4e7-7e0f94dfdf9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDM2MjQsIm5iZiI6MTcyNzgwMzMyNCwicGF0aCI6Ii8yMDcwMjU4NC8zNzIyNjExNTItODU3YzM1Y2ItZGE3NS00MTFjLWI0ZTctN2UwZjk0ZGZkZjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE3MjIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNzhjMDZiMDI3MTdmMDZmMjEyNWE1MmMzZGYyYzE1MmUzZGI3NzM1MDA0Nzc2YTE0YzI1MmRhYWJkZTVhOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0P1DWz_1ux_uNayP1d1Q2izN1Q3i1nCSKHhLj_CVMfQ) Add username > get new query

thanks
