### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by WizRome0** [Freddywhest/MemeFiBot-New#36]
*Can it auto kill monsters, if yes can I change the amount of damage delt to the monster and what value should I not exceed to be safe? 
*I was to use my main account (just one account), do I need to use proxy, if yes will Node.js do? 
*Is it safe to use on main account?
*What values do you recommend i should use to avoid getting detected by MEMEFI? 
Thanks in advance 👍 👍 👍...

**Comment by Freddywhest** [comment]
Use default settings
