### ISSUE TITLE
multi account

### ISSUE THREAD

**Issue by amirnajm** [Freddywhest/MemeFiBot-New#38]
Hello sir thanks for your good bot
i want to know its not possible to use mulyi query? for 5 accounts?

**Comment by Color-maN** [comment]
> Здравствуйте, сэр, спасибо за вашего хорошего бота я хочу знать, невозможно использовать множественный запрос? для 5 аккаунтов?

Я использую 11 и все хорошо, попробуй использовать прокси, может быть сервер игры не позволяет делать такое количество запросов с одного адреса.

**Comment by Color-maN** [comment]
> у меня есть прокси, просто хочу узнать, возможно это или нет, спасибо за помощь еще один вопрос: я отключил turbo boost, но он всегда им пользуется, и как я могу выполнять задачи clam?

Вы изменили настройки AUTO_APPLY_TURBO=False в файле .env? Чтобы выполнялись задания нужно настроить следующие строки AUTO_COMPLETE_TASKS=True, DELAY_BETWEEN_TASKS=[21, 37], правда последние пару часов у меня выдает ошибки на верификацию заданий (а еще примечание, бот выполняет ТОЛЬКО задания с YOUTUBE!, не видел чтоб он выполнял подписки на каналы и пр)

**Comment by amirnajm** [comment]
> > i have a proxy just want to know if it is possible or not thanks for the help one more question i disabled turbo boost but he always uses it and how can i do clam tasks?
> 
> Have you changed the AUTO_APPLY_TURBO=False settings in the .env file? To run the tasks, you need to set the following lines AUTO_COMPLETE_TASKS=True, DELAY_BETWEEN_TASKS=[21, 37], although for the last couple of hours I have been getting errors on task verification (and another note, the bot ONLY runs tasks from YOUTUBE!, I have not seen it run subscriptions to channels, etc.)

yes i did all of this in .env-example file but nothing didnt change

**Comment by amirnajm** [comment]
i just want to bypass tasks dont wana risk for taps

**Comment by Color-maN** [comment]
> да, я сделал все это в файле .env-example, но ничего не изменилось

Вот я и спросил, почему то файл INSTALL.bat выполняет все команды кроме copy .env-example .env (что создает новый файл в папке с расширением .env с тем же набором правил), только тогда вопрос как вы смогли запустить бота без API ID и API HASH. Попробуйте создать копию файла .env-example в том же месте, только с расширением .env, содержимое обоих должно быть одинаковым.

Если вы на Windows, запустите в папке с ботом Терминал и введите: copy .env-example .env

**Comment by amirnajm** [comment]
> > yes i did all this in .env-example file but nothing changed
> 
> So I asked why the INSTALL.bat file executes all commands except copy .env-example .env (which creates a new file in the folder with the .env extension with the same set of rules), only then the question is how you were able to launch the bot without API ID and API HASH. Try creating a copy of the .env-example file in the same place, only with the .env extension, the contents of both should be the same.
> 
> If you are on Windows, launch Terminal in the folder with the bot and enter: copy .env-example .env
![image](https://github.com/user-attachments/assets/11126b03-0cb0-417c-9769-73657a0eeb9d)

im sorry for too many questions, im using linux , i used query id and thought dony need to api id, i used 'false' for all setting except auto claim tasks but still nothing happens

**Comment by Color-maN** [comment]
> прошу прощения за слишком много вопросов, я использую linux, я использовал идентификатор запроса и подумал, что мне не нужен идентификатор api, я использовал 'false' для всех настроек, кроме задач автоматического утверждения, но по-прежнему ничего не происходит

Я так понял что вы хотите использовать только DELAY_BETWEEN_TASKS ?
У вас и правда отключены TURBO_TAPS, а вот обычные тапы выключить нельзя, такая функция не предусмотрена, но попробуйте в качестве идеи выставить параметр MIN_AVAILABLE_ENERGY под максимальный заряд энергии.

**Comment by amirnajm** [comment]
> > sorry for too many questions, i'm using linux, i used request id and thought i don't need api id, i used 'false' for all settings except auto approval tasks but still nothing happens
> 
> I understand that you want to use only AUTO_COMPLETE_TASKS? You really have TURBO_TAPS disabled, but you can't turn off regular taps, such a function is not provided, but try setting the MIN_AVAILABLE_ENERGY parameter to the maximum energy charge as an idea.

ok thank you
one last question shold i rename .env-example to .env?

**Comment by Color-maN** [comment]
> хорошо, спасибо последний вопрос, если я переименую .env-example в .env?

Вообще файл .env-example не нужен для работы бота, он и именуется как "пример", для работы нужен только файл .env

Так что смело можете переименовать.

**Comment by amirnajm** [comment]
> > ok thanks last question if i rename .env-example to .env?
> 
> In general, the .env-example file is not needed for the bot to work, it is called "example", only the .env file is needed for work
> 
> So feel free to rename it.

where is this env file? i just see env-example

**Comment by Color-maN** [comment]
> где этот env-файл? я просто вижу env-пример

Возможно переводчик плохо работает и вы меня не понимаете. Файла .env изначально нету, создайте его сами и вставьте туда тоже самое, что для .env-example

**Comment by amirnajm** [comment]
i didnt understand really,think i cant use this,
anyway thank mr fredy for codes.

**Comment by Color-maN** [comment]
> я действительно не понял, думаю, что не смогу это использовать, в любом случае, спасибо мистеру Фредди за коды.

Просто настройте файл ".env-example" и переименуйте его в ".env".

**Comment by Color-maN** [comment]
Вот так это выглядит на windows, у вас также должна быть включена видимость расширения файлов.
![Без имени](https://github.com/user-attachments/assets/9b5133b8-dcf4-48c3-8521-1e865232f542)

**Comment by amirnajm** [comment]
> This is how it looks on windows, you also need to have file extension visibility enabled. ![No name](https://private-user-images.githubusercontent.com/180790696/373064154-9b5133b8-dcf4-48c3-8521-1e865232f542.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MTE3OTMsIm5iZiI6MTcyNzkxMTQ5MywicGF0aCI6Ii8xODA3OTA2OTYvMzczMDY0MTU0LTliNTEzM2I4LWRjZjQtNDhjMy04NTIxLTFlODY1MjMyZjU0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQyMzI0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGMzMTE5NzQzN2ZmNjlhNGNkMTA0YjI1MDI5MjE2ZjEwN2M2MGUxZWFhN2I4MGQ1MTUwMzM2OWE3YjM2OTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UTmcs8XMLQeHXRRNuEGrqm3dAy0QDSoXpCiyWZA9Pgs)

thank you my friend but in windows i always face with error like set username and delete cache folder,even when i done this actions still dont work for me :( i saw some people that only get tasks for spins with scripts , in github only this repository have auto clam task option

**Comment by Color-maN** [comment]
> спасибо, мой друг, но в Windows я всегда сталкиваюсь с ошибкой типа "Установить имя пользователя" и "удалить папку кэша", даже когда я выполнял эти действия, у меня все равно ничего не получалось: ( я видел некоторых людей, которые получают задачи только для спинов со скриптами, в github только в этом репозитории есть опция автоматической отправки задач

Отправь пожалуйста фото, чтоб я увидел какие файлы в папке с ботом.

**Comment by amirnajm** [comment]
> > thanks my friend, but in windows i always face error like "set username" and "delete cache folder", even when i did these steps i still couldn't get it working :( i saw some people who only get tasks for spins with scripts, in github only this repository has auto submit tasks option
> 
> Please send a photo so I can see what files are in the folder with the bot.

this is all i have and changed

**Comment by Color-maN** [comment]
Подскажи какой у тебя минимальный заряд батареи на аккаунте?

**Comment by amirnajm** [comment]
> Tell me what is the minimum battery charge on your account?

![image](https://github.com/user-attachments/assets/e6599a4a-010c-4640-8528-2a9f46188c83)
i dont know wich one is battery send you shot

**Comment by Color-maN** [comment]
Попробуй заменить свои настройки на эти:

API_ID=
API_HASH=

RANDOM_TURBO_TAPS=[0,0]
RANDOM_TAPS=[0,0]

AUTO_APPLY_TURBO=False
AUTO_APPLY_ENERGY=False

AUTO_UPGRADE_DAMAGE=False
MAX_DAMAGE_LEVEL=0

AUTO_UPGRADE_RECHARGE=False
MAX_RECHARGE_LEVEL=0

AUTO_UPGRADE_ENERGY=False
MAX_ENERGY_LEVEL=0

AUTO_BUY_TAPBOT=False
AUTO_CLAIM_AND_START_TAPBOT=False
AUTO_SPIN=False

AUTO_COMPLETE_TASKS=True

MIN_AVAILABLE_ENERGY=11499

SLEEP_BETWEEN_REQUESTS=[10,15]

DELAY_BETWEEN_TURBO=[0,0]

DELAY_BETWEEN_TAPS=[0,0]

DELAY_BETWEEN_TASKS=[16,27]

USE_REGISTRATION_PROXY=False

USE_PROXY_FROM_JS_FILE=False

USE_PROXY_FROM_TXT_FILE=False

DELAY_BETWEEN_STARTING_BOT=[3,19]

**Comment by Color-maN** [comment]
Тапать он конечно все равно будет, но немного.

**Comment by amirnajm** [comment]
> Of course, he will still tap, but not much.

how can i thank you my friend are you mr fredy to buy a coffe for you? you solved .... but for last help how can i place 5 query? is it ok if i just copy them in 1 column?

**Comment by Color-maN** [comment]
> как я могу поблагодарить тебя, мой друг, ты мистер Фредди, за то, что я купил тебе кофе? ты решил .... но в качестве последней помощи, как я могу разместить 5 запросов? ничего, если я просто скопирую их в 1 столбец?

Спасибо, я не создатель бота, а такой же пользователь. Остальные сессии можно добавить таким же образом через "query_id", но желательно не забывать использовать прокси. Если проблема решена, можете ее закрыть.

**Comment by amirnajm** [comment]
> > how can i thank you my friend you mr freddy for buying you coffee you decided.... but as a last resort how can i post 5 requests is it ok if i just copy them into 1 column?
> 
> Thank you, I am not the creator of the bot, but a fellow user. Other sessions can be added in the same way via "query_id", but it is advisable not to forget to use a proxy. If the problem is solved, you can close it.
{
  "account": "query_id="
              "query_id="
}
  like this?

**Comment by Color-maN** [comment]
I don't know. I don't use "query_id".

**Comment by Mysyxx** [comment]
how to multi accounts using query?
