### ISSUE TITLE
Enable SOCKS5 Proxy and Add PM2 Action Argument

### ISSUE THREAD

**Issue by Gareryer** [Freddywhest/MemeFiBot-New#4]
1. Enable SOCKS5 Proxy Support
Currently, only HTTP and HTTPS proxies are supported:

```protocol: "http", // Proxy protocol [http/https]```
Extend proxy support to include SOCKS5 protocol, allowing the following:
```protocol: "socks5"```

2. Add PM2 Action Argument for start-action
Currently, actions are executed separately, but we need to streamline the process when using PM2.

Request:
Support passing action arguments on a single line for use cases like PM2. The desired command format is:
```pm2 start npm --name $app-name -- run start-action2```
Update the scripts section of package.json to include:
```
"scripts": {
  "test": "echo \"Error: no test specified\" && exit 1",
  "start-action1": "node index.js --action=1",
  "start-action2": "node index.js --action=2"
}
```

**Comment by Freddywhest** [comment]
Is it premium proxies? If yes then the protocol does not matter. Just set the protocol  to http and add your ip, port, ....

**Comment by Freddywhest** [comment]
For the PM2 Action Argument, add it and make a pull request

**Comment by Freddywhest** [comment]
Done
