### ISSUE TITLE
proxy tittle

### ISSUE THREAD

**Issue by zhangmo235** [Freddywhest/MemeFiBot-New#40]
![为啥6(1)](https://github.com/user-attachments/assets/b2cb5354-0abb-4314-b175-e56e7432991a)

**Comment by zhangmo235** [comment]
I filled in the required format and it showed this error. I checked the proxy and there was no problem.

**Comment by Freddywhest** [comment]
type://user:pass@ip:port
type://user:pass:ip:port
type://ip:port:user:pass
type://ip:port@user:pass
type://ip:port

The proxy should be any of this format

**Comment by zhangmo235** [comment]
I filled it out according to this format, you can take a look at the screenshot

**Comment by Freddywhest** [comment]
Use a different, There a 5 formats

**Comment by zhangmo235** [comment]
i try all type

**Comment by Freddywhest** [comment]
Use IP instead of host name

**Comment by zhangmo235** [comment]
OK i try it boss
