### ISSUE TITLE
new comer problem

### ISSUE THREAD

**Issue by amirnajm** [Freddywhest/MemeFiBot-New#41]
⏳ Processing request is taking a little longer than usual. Retrying in 300 seconds.

hello sir, i was using bot from last night but never seen this phrase, what is this for? i did not change anything

**Comment by Freddywhest** [comment]
Use proxies

**Comment by amirnajm** [comment]
> Use proxies

already have 100 proxy in file, it was working working correctly till 1 hour ago :(

**Comment by amirnajm** [comment]
if you dont have mood to response users, its easy just dont use github, you dont have to be here and act like this close questions without answers, mofu

> Use proxies
