### ISSUE TITLE
used your sessionconvertor from telethon to gramjs, input my session file to sessions folder correctly, used proxy and this happen.

### ISSUE THREAD

**Issue by revansyahallam** [Freddywhest/MemeFiBot-New#42]
![image](https://github.com/user-attachments/assets/e2b63bbf-99a7-42fd-80e1-7c3b1fd08130)

**Comment by revansyahallam** [comment]
tested non-proxy or using a proxy, still the same

I tested my old account where the boss is at level 20, but I still got the same error.

**Comment by revansyahallam** [comment]
tried to use the node 18, no work
tried to use node 20, no work

**Comment by toastyy00** [comment]
any fix?

**Comment by Freddywhest** [comment]
Try using using query_id or create a new session with the bot
