### ISSUE TITLE
Unknown error during Authorization: FetchClientError: Request failed with status code: 500

### ISSUE THREAD

**Issue by DvoeglazovIlya** [Freddywhest/MemeFiBot-New#5]
node version 
v20.11.1
on Debian 12

[2024-09-25 16:01:12] | ERROR | [memefi] | new_ilya | ❗️Unknown error during Authorization: FetchClientError: Request failed with status code: 500

I try converted sessions from SessionConvertor - got this error

Also tryed after created new session through bot MemeFiBot-New - got this error

**Comment by Freddywhest** [comment]
Try
https://github.com/Freddywhest/MemeFiBot-New/issues/3#issuecomment-2373515951
