### ISSUE TITLE
Processing request is taking a little longer than usual

### ISSUE THREAD

**Issue by ravindu-piumantha** [Freddywhest/MemeFiBot-New#51]
![Screenshot 2024-10-13 064120](https://github.com/user-attachments/assets/61b2eeb3-3e72-4321-915c-7718da5974dc)

how to solve this

**Comment by Freddywhest** [comment]
Use proxies

**Comment by ravindu-piumantha** [comment]
already using proxies

**Comment by Freddywhest** [comment]
Then stop the bot for 10-12hrs and try again
