### ISSUE TITLE
about proxy

### ISSUE THREAD

**Issue by supmyhava** [Freddywhest/MemeFiBot-New#53]
i see that for every session i need to add a line in proxy.txt
so ifi have 3 accounts i need 3 lines in proxy 
how it is working ? each line is account ? and how it chose what proxy going to what account
btw i have 1 proxy and 3 accounts so i just paste my proxy 3 times in the txt file that way all accounts will get the same proxy

**Comment by Color-maN** [comment]
> поэтому я просто вставляю свой прокси-сервер 3 раза в файл txt, чтобы все аккаунты получали один и тот же прокси-сервер

твоя идея должна сработать, каждая срока по очереди (Сверху-Вниз) в прокси распределяется по порядку алфавита имен сессий в папке "sessions".
