### ISSUE TITLE
Task codes

### ISSUE THREAD

**Issue by sprtstr** [Freddywhest/MemeFiBot-New#62]
ERROR - Task requires verification code but no codes found. Skipping...
how to solve this issue?

**Comment by Color-maN** [comment]
> ОШИБКА — для выполнения задачи требуется код подтверждения, но коды не найдены. Пропуская... как решить эту проблему?

Это говорит о том, что в базе данных для бота нет доступных кодов для ввода определенного задания. Чтобы решить эту проблему, вы можете использовать свои коды из файла codes.json, редактируя их вручную или дождаться обновления кодов с базы данных.

Также чтобы это пока что не мешало, можно сделать так - AUTO_TASKS=False.
