### ISSUE TITLE
 | ERROR | [memefi] | luna |❗️Unknown error during Authorization: FetchClientError: Request failed with status code: 403

### ISSUE THREAD

**Issue by yopiucing** [Freddywhest/MemeFiBot-New#66]
![image](https://github.com/user-attachments/assets/dfddfab1-d0f7-41ff-aeea-971166b9e2f4)

**Comment by Freddywhest** [comment]
Your query id is not valid. Get a new query id

**Comment by yopiucing** [comment]
but i am using session

Pada Sen, 28 Okt 2024, 15.03, Alfred Nti ***@***.***> menulis:

**Comment by Freddywhest** [comment]
This is strange, is a new memefi account?

**Comment by yopiucing** [comment]
nope its main account i usually used

Pada Sen, 28 Okt 2024, 16.24, Alfred Nti ***@***.***> menulis:
