### ISSUE TITLE
 Error while getting access token: Request failed with status code: 403

### ISSUE THREAD

**Issue by Odipus40** [Freddywhest/MemeFiBot-New#8]
Error while getting access token: Request failed with status code: 403
 
 How to fix?

**Comment by Inquisitor007** [comment]
Error while getting access token (Forbidden)

I have this error on one account

**Comment by painterzeou** [comment]
> Error while getting access token (Forbidden)
> 
> I have this error on one account

Same

**Comment by Freddywhest** [comment]
Read here
https://github.com/Freddywhest/MemeFiBot-New/issues/3#issuecomment-2373515951

**Comment by painterzeou** [comment]
> Read here [#3 (comment)](https://github.com/Freddywhest/MemeFiBot-New/issues/3#issuecomment-2373515951)



> Read here [#3 (comment)](https://github.com/Freddywhest/MemeFiBot-New/issues/3#issuecomment-2373515951)

Nope not working

**Comment by Freddywhest** [comment]
I can't reproduce the error as I'm not encountering it. I tested with more than 15 accounts, and they all worked. Please update the script and try again.
